---
title: "Final Consensu Graph (Stage 22 Xenopus embryo)"
output:
  html_document:
    df_print: paged
---

```{r, echo=FALSE, fig.height=10}
load("~/Desktop/XenoK5_4.RData")

suppressWarnings(library(rgl))
suppressMessages(library(igraph))

# open3d()

# par3d("windowRect"= c(0,0,1000,1000))
# rgl.viewpoint(  zoom = .7 )

plot3d(Graph.FR.1, col = V(ExpData.Graph.Fil.2)$col, alpha = .5, xlab = "x axis", ylab = "y axis", zlab = "z axis")

TargetEdgs_0 <- CG.Emb.B.2$NodePositions[CG.Emb.B.2$Edges$Edges[,1],]
TargetEdgs_1 <- CG.Emb.B.2$NodePositions[CG.Emb.B.2$Edges$Edges[,2],]
for(j in 1:nrow(TargetEdgs_1)){
  segments3d(x = rbind(TargetEdgs_0[j, 1], TargetEdgs_1[j, 1]),
          y = rbind(TargetEdgs_0[j, 2], TargetEdgs_1[j, 2]),
          z = rbind(TargetEdgs_0[j, 3], TargetEdgs_1[j, 3]),
          col = "black", alpha = .8, lwd = 2)
}

rglwidget()

```

The following color scale is used to represent cell type

```{r color, echo=FALSE}
ColVect <- V(ExpData.Graph.Fil.2)$col
names(ColVect) <- V(ExpData.Graph.Fil.2)$type

ColVect <- ColVect[!duplicated(ColVect)]

par(mar=c(0, 15, 0, 0))

barplot(rep(1, length(ColVect)), horiz = TRUE, col = ColVect, border = NA,
        names.arg = names(ColVect), las = 2, cex.names = .6)
```




